### GET all owners
GET http://localhost:3000/api/owners
Accept: application/json

###

### GET owners with pagination
GET http://localhost:3000/api/owners?page=1&limit=2
Accept: application/json

###

### GET a specific owner by ID
GET http://localhost:3000/api/owners/d80c86b7-a873-407d-a98b-af9c53ff9d69
Accept: application/json

###

### Create a new owner
POST http://localhost:3000/api/owners
Content-Type: application/json

{
  "first_name": "Tata",
  "phone": "1234567890",
  "email": "haha@outlook.fr",
  "last_name": "Toto",
  "adress": "157 rue gauagz"
}

###
### Update an existing owner
PUT http://localhost:3000/api/owners/2595b44a-87d3-40fe-8a2b-bb21c6ba5157
Content-Type: application/json

{
  "first_name": "MODIFF TATA",
  "phone": "1234567890",
  "email": "haha@outlook.fr",
  "last_name": "Toto", 
  "adress" : "123 Main St"
}

###
### Delete an owner
DELETE http://localhost:3000/api/owners/dda27015-8a8f-4a6f-bb42-ee93edd8494
Content-Type: application/json

###

### TEST middleware 
GET http://localhost:3000/api/owners/_test/crash
Accept: application/json