@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiYWNjMGQ1NzEtOWFlNy00ZTEwLWIxMTUtMDBjM2FkMjI5MDI4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4ODE3MTE2LCJleHAiOjE3Njg4MjA3MTZ9.-n_en62zJfO0Kx5yNcXJKE2o1geOcbXetdc1_NboKE0

### GET all animals
GET http://localhost:3000/api/animals
Authorization: Bearer {{admin_token}}
Accept: application/json

###

### GET a specific animals by ID
GET http://localhost:3000/api/animals/4a89596e-911e-45b3-bc94-42965a3ed367
### Create a new animals
POST http://localhost:3000/api/animals
Content-Type: application/json
Accept: application/json

{
  "id_owner": "ae0f62b5-c30a-40ed-8cc7-51f88e20e765",
  "name": "Dupont",
  "breed": "Labrador",
  "chip_number": "123456789",
  "birth_date": "2025-12-17T00:00:00.000Z",
  "weight": 30,
  "size": 60,
  "photo": "http://example.com/photo.jpg"
}

###

### Update an existing animals
PUT http://localhost:3000/api/animals/b15d6bb4-4462-4cee-9d3b-3c831672af31
Content-Type: application/json

{
  "id_owner": "ae0f62b5-c30a-40ed-8cc7-51f88e20e765",
  "name": "Dupont",
  "breed": "Labrador",
  "chip_number": "1234556789",
  "birth_date": "2025-12-17T00:00:00.000Z",
  "weight": 30,
  "size": 60,
  "photo": "http://example.com/photo.jpg"
}

###

### Delete a animals
DELETE http://localhost:3000/api/animals/b15d6bb4-4462-4cee-9d3b-3c831672af31
###
