### GET all owners
GET http://localhost:3000/api/owners
Accept: application/json

###

### GET owners with pagination
GET http://localhost:3000/api/owners?page=1&limit=2
Accept: application/json

###

### GET a specific owner by ID
GET http://localhost:3000/api/owners/859eee7d-60cd-4a2c-b9aa-5257f38b9fc2
Accept: application/json

###

### Create a new owner
POST http://localhost:3000/api/owners
Content-Type: application/json
#  Id user à recuperer depuis table user une fois user créé
{
  "id_user": "f07116bf-b44f-42b9-9eb9-39c57653d353", 
  "first_name": "Tata",
  "phone": "1234567890",
  "email": "haha@outlook.fr",
  "last_name": "Toto",
  "adress": "157 rue gauagz"
}

###
### Update an existing owner
PUT http://localhost:3000/api/owners/ae0f62b5-c30a-40ed-8cc7-51f88e20e76
Content-Type: application/json

{
  "first_name": "MODIFF TATA",
  "phone": "1234567890",
  "email": "haha@outlook.fr",
  "last_name": "Toto", 
  "adress" : "123 Main St"
}

###
### Delete an owner
DELETE http://localhost:3000/api/owners/dda27015-8a8f-4a6f-bb42-ee93edd8494
Content-Type: application/json

###

### TEST middleware 
GET http://localhost:3000/api/owners/_test/crash
Accept: application/json