@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoiYWNjMGQ1NzEtOWFlNy00ZTEwLWIxMTUtMDBjM2FkMjI5MDI4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4ODExMzU2LCJleHAiOjE3Njg4MTQ5NTZ9.ta5OHOgo9WoV1Hi8JZDL0QnPas2Z5RAHhTY0q8WDiLM
### GET all users
GET http://localhost:3000/api/users
Authorization: Bearer {{admin_token}}
Accept: application/json
###

### GET a specific user by ID
GET http://localhost:3000/api/users/19aaf6ba-9b18-4a6e-bce8-b31ec282d8a4
Authorization: Bearer {{admin_token}}
Accept: application/json

###

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "first_name": "Tata",
  "phone": "1234567890",
  "email": "kiki@outlook.fr",
  "password": "password123",
  "last_name": "Toto",
  "adress": "157 rue gauagz",
  "user_role": "admin"
}

###

### Update an existing user
PUT http://localhost:3000/api/users/19aaf6ba-9b18-4a6e-bce8-b31ec282d8a4
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "first_name": "Tata",
  "phone": "1234567890",
  "email": "kkokoza@outlook.fr",
  "password": "password123",
  "last_name": "Toto",
  "adress": "157 rue gauagz",
  "user_role": "veterinarian"
}

###
### Delete an user
DELETE http://localhost:3000/api/users/dda27015-8a8f-4a6f-bb42-ee93edd8494
Authorization: Bearer {{admin_token}}
Content-Type: application/json
